name: act9
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  flutter_animate: ^4.2.0
  flutter_hooks: ^0.20.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  # Enables Material Design icons
  uses-material-design: true

  # Asset directories
  assets:
    - assets/images/
    - assets/sounds/
